name: 🐍 Bug Report
description: Report a bug.
title: "[BUG] Title here"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! We are going to make our OS bug-free.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of our OS are you running?
    validations:
      required: true
  - type: dropdown
    id: runner
    attributes:
      label: How did you run the OS?
      multiple: true
      options:
        - QEMU
        - VirtualBox
        - VMware Workstation Player
        - VMware Workstation Pro
        - Other OS
        - Phisically installed OS
    validations:
        required: true
  - type: textarea
    id: out
    attributes:
      label: Output
      description: Please copy and paste any output. This will be automatically formatted into code. If no output present, just skip.
      render: shell
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: What do you want to add to this issue?
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/RawBerryTeam/RawBerry/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true