name: 🚀 Feature request
description: Tell us what do you want to see in this OS!
title: "[FEATURE] Title here"
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! We are going to make our OS best and bug-free.
  - type: textarea
    id: what
    attributes:
      label: What do you want to see in this project?
      description: Tell everything that you want to be in the project. Use MarkDown
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: What do you want to add to this issue?
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Interpuce/AurorOS/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true